sudo: false
language: python
cache: pip

env:
  global:
    CLUSTERCOOKIE=2F1B4760251B51783700055F1A037271685A64680A1450722A4656722A0B1D6438091D68251C4F65381C526F380A4A412C0552682746506E26

matrix:
  include:
    - python: 3.6
      env: RUN_PEP8=--pep8

before_install:
# Install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv

- pip install --quiet $PRE -r requirements/test.txt
- pip install --quiet spiceypy --no-cache-di

# Install CDF library
- wget https://cdaweb.sci.gsfc.nasa.gov/pub/software/cdf/dist/cdf37_0/linux/cdf37_0-dist-all.tar.gz
- tar -zxvf cdf37_0-dist-all.tar.gz
- cd cdf37_0-dist
- make OS=linux ENV=gnu all
- make INSTALLDIR=~/cdf install
- PATH=~/cdf:$PATH
- cd ../

script:
# Check that unit tests work
- pytest heliopy/ --cov=heliopy/ -v --durations=5 $RUN_PEP8
# Check building a source distribution works
- python setup.py sdist
after_success:
- pip install codecov
- codecov
