dist: trusty
language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
      env: RUN_PEP8=--pep8
    - python: 'nightly'
      env: PRE=--pre

  allow_failures:
    - python: "nightly"


before_install:
# Install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv

- pip install --quiet -r $PRE requirements/test.txt
- pip install --quiet spiceypy --no-cache-di

# Install CDF library
- wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf36_3_1/linux/cdf36_3_1-dist-all.tar.gz
- tar -zxvf cdf36_3_1-dist-all.tar.gz
- cd cdf36_3-dist
- make OS=linux ENV=gnu all
- sudo make INSTALLDIR=/usr/local/cdf install
- cd ../

script:
# Check that unit tests work
- pytest heliopy/ --cov=heliopy/ -v --durations=5 $RUN_PEP8
# Check building a source distribution works
- python setup.py sdist
after_success:
- pip install codecov
- codecov
