sudo: required
language: python
python:
  - "3.5"

# Download and set up conda
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Update conda itself
  - conda update --yes conda
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION scipy
  - source activate testenv
  # Install other dependancies
  - pip install pytest pytest-cov coveralls pandas
  - pip install spacepy
script:
  - py.test heliopy/ --cov=heliopy/
after_success:
  - coveralls
