
deps-run: &deps-install
  name: Install dependencies
  command: |
    apt update
    apt install -y graphviz
    python3 -m venv venv
    . venv/bin/activate
    pip install --user --progress-bar off -r requirements/docs.txt
    pip install --user --progress-bar off .

doc-test: &doc-test
  name: Run doctets
  command: make doctest
  working_directory: doc

doc-run: &doc-build
  name: Build documentation
  command: make html SPHINXOPTS='-W -q'
  working_directory: doc

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-test
      - run: *doc-build
      - store_artifacts:
          path: doc/build/html
      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/doc/build/html/index.html"

notify:
  webhooks:
    - url: https://giles.cadair.com/circleci
